### ISSUE TITLE
Does elm-format build with stack 1.9?

### ISSUE THREAD

**Issue by avh4** [avh4/elm-format#601]
Someone reported in elm slack:

```
stack19116/indents-0.3.3/Text/Parsec/Indent.hs:21:1: error:
        Could not find module 'Control.Concatenative'
        There are files missing in the 'concatenative-1.0.1' package,
        try running 'ghc-pkg check'.
        Use -v to see a list of the files searched for.
```
when building using stack 1.9.3.

Haven't had time to verify yet, but this possibly could be a problem when using new versions of stack.  (Or it could be some unrelated problem with the OP's local setup)

**Comment by rl-king** [comment]
This ended up being an issue with the OP's (me) setup. Recloning the repo solved the issue, not sure what caused it though. It does build fine with stack 1.9.3
